sudo: false
language: go
go:
  - '1.6'
  - '1.7'
  - '1.8'
  - '1.9'
  - tip
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "KGRKISvv9xOe/oGh28gSN6h+IALUTPAkqjkV4zq2yV5QuTmyvm24LBG5GbMAZB9sEcLaOFwOBB7hg8GLKj46Ae3wV2TxBlaSY62N888C080zGlQFxNlF5z281Dsk71zKoHhxYgq9K6VSmmIU8LFcmY+M0jBJzsoAnANBjjGGl9s=\n"
before_install:
  - sudo apt-get install -y nodejs
  - npm install -g snyk
install:
  - go get -t ./...
  - snyk test --org=maxmind
after_success:
  - snyk monitor --org=maxmind --project-name=maxmind/geoip2-csv-converter
env:
  global:
    secure: "b5M6hkol2NU0QkTVGj/oxoCU3LoVJEd3t+fECkOHXZqvUXkcxOXVF1L36TyPThnStkdJkCvqjiUo3Km5ga+q8R9plCfTqKNLHCsZlEYQgTxOV3ob1nk+PjRgI8jRQpYtOGGTybtx3FpNh+/T795jXmEhktMK0idCJ/ESoQvMhvs="
