---
sudo: false
language: go
go:
  - '1.6'
  - '1.7'
  - '1.8'
  - '1.9'
  - tip
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "KGRKISvv9xOe/oGh28gSN6h+IALUTPAkqjkV4zq2yV5QuTmyvm24LBG5GbMAZB9sEcLaOFwOBB7hg8GLKj46Ae3wV2TxBlaSY62N888C080zGlQFxNlF5z281Dsk71zKoHhxYgq9K6VSmmIU8LFcmY+M0jBJzsoAnANBjjGGl9s=\n"
